name = input("What is your name?: ")
print("Nice to meet you " + name + "!" + " I am Leo from the USA." )
country = input("Where are you from?: ")
print("wow! " + country + " is a beautiful country. Isn't is?")
answer = input("Answer: ")
print("I really love you country because everything there is well organize.")
question1 = input("So where do you live know?: ")
print("Really! This is amazing we are neighbors!")
question3 = input("How long have you been here " + question1 + "?:")
print("Wow! you just live here " + question3 + " like my friend Jhon." +  " He have been here only for " +
      question3 + " in the USA too.")
question4 = input("Do you mind if i have your phone number?: ")
print("Thank so much " + name + " i really appreciate it. mine is 860 862 1352. I will call you tomorrow.")
print("Good bye!")
question5 = input("Once again thanks.")
