apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-nodeport-service # the name of the service
  labels:
    app: front-end
spec:
  type: NodePort # or LoadBalancer # ExternalName # ClusterIp
  selector: # to define where to send the traffic
    app: myapp # to send  the traffic only to pods that matches this label defined in the pod definition file
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
      nodePort: 31231 # NodePort to access our app from the browser 
      # The default node port range for Kubernetes is 30000 - 32767

  
#----------------------------------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-nodeport-service 
  labels:
    app: front-end
spec:
  type: NodePort 
  selector: 
    app: myapp
  ports: 
    - name: http
      port: 80 
      targetPort: 80
      nodePort: 31231  